// WARNING: DO NOT EDIT. This file is
// automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: 'eu-west-1',
  aws_cognito_identity_pool_id: 'eu-west-1:f9ab09bb-4bda-4148-9063-d41441010423',
  aws_cognito_region: 'eu-west-1',
  aws_user_pools_id: 'eu-west-1_Gxole34Bt',
  aws_user_pools_web_client_id: '46072qfekom0c13p5jl61guo7q',
  oauth: {
    domain: 'bookmarks58417305-58417305-prod.auth.eu-west-1.amazoncognito.com',
    scope: [
      'phone',
      'email',
      'openid',
      'profile',
      'aws.cognito.signin.user.admin',
    ],
    redirectSignIn: 'http://localhost:8080/,https://bookmarks.materiajs.com/',
    redirectSignOut: 'http://localhost:8080/,https://bookmarks.materiajs.com/',
    responseType: 'code',
  },
  federationTarget: 'COGNITO_USER_POOLS',
  aws_appsync_graphqlEndpoint: 'https://ajqru5thqrfw7fa6v36ozuypmy.appsync-api.eu-west-1.amazonaws.com/graphql',
  aws_appsync_region: 'eu-west-1',
  aws_appsync_authenticationType: 'AMAZON_COGNITO_USER_POOLS',
};


export default awsmobile;
